const PDFDocument = require("pdfkit");
const Expense = require("../models/Expense");
const Income = require("../models/Income");

class ReportController {
    // GENERATE FINANCIAL REPORT PDF
    async generateFinancialReport(req,res) {
        try {
            //  FETCH DATA 
            const expenses = await Expense.find({user: req.user._id}).sort({createdAt: -1});
            const incomes = await Income.find({user: req.user._id}).sort({createdAt: -1});

            //  TOTALS 
            const totalExpense = expenses.reduce((acc, item) => acc + item.amount, 0);
            const totalIncome = incomes.reduce((acc, item) => acc + item.amount, 0);

            const totalSavings = totalIncome - totalExpense;

            // CREATE PDF 
            const doc =new PDFDocument({margin: 50});

            // RESPONSE HEADERS 
            res.setHeader("Content-Type","application/pdf");
            res.setHeader("Content-Disposition","attachment; filename=financial-report.pdf");
            res.setHeader("Cache-Control","no-cache");
            //FONT
            doc.registerFont("Noto","./fonts/NotoSans-Regular.ttf");
            doc.font("Noto");
            // Pipe PDF
            doc.pipe(res);

            //  TITLE 
            doc.fontSize(24).text("Financial Report",
                {
                    align: "center"
                }
            );
            doc.moveDown();

            //  SUMMARY 
            doc.fontSize(18).text("Summary");
            doc.moveDown(0.5);
            doc.fontSize(12).text(`Total Income: ₹${totalIncome}`);
            doc.text(`Total Expense: ₹${totalExpense}`);
            doc.text(`Total Savings: ₹${totalSavings}`);
            doc.moveDown();

            //  INCOME SECTION 
            doc.fontSize(18).text("Income Details");
            doc.moveDown(0.5);
            incomes.forEach((income) => {
                doc.fontSize(12).text(`${income.source} | ₹${income.amount} | ${income.category}`);
            });
            doc.moveDown();

            //  EXPENSE SECTION 
            doc.fontSize(18).text("Expense Details");
            doc.moveDown(0.5);

            expenses.forEach((expense) => {
                doc.fontSize(12).text(`${expense.title} | ₹${expense.amount} | ${expense.category}`);
            });
            doc.moveDown();

            // FOOTER 
            doc
            .fontSize(10)
            .text(
                "Generated by AI Financial Advisor",
                {
                    align: "center"
                }
            );
            // Finalize PDF
            doc.end();
        } catch (error) {
            return res.status(500).json({
                success: false,
                message: error.message
            });
        }
    }
}

module.exports = new ReportController();